### ISSUE TITLE
[Suggestion] Sound issues.

### ISSUE THREAD

**Issue by Qee1y** [YUNG-GANG/YUNGs-Better-End-Island#12]
It's strange that when a tower is activated and explodes, but the explosion has no sound and is very quiet, which only makes people feel strange.

**Comment by yungnickyoung** [comment]
Are you using a sound mod like Sound Physics Remastered? It could be a mod like that interfering with the sounds.

**Comment by Qee1y** [comment]
Yes.  But how to solve this problem, but I don't want to delete this mod

**Comment by yungnickyoung** [comment]
Marking this as duplicate of #19
