### ISSUE TITLE
Dragon doesn't spawn with other end mods

### ISSUE THREAD

**Issue by CageyPower** [YUNG-GANG/YUNGs-Better-End-Island#14]
Dragon does not spawn when using other end mods such as Stellarity. Summon command also does not work.

**Comment by SiverDX** [comment]
Dragon does not spawn when using ~~other end mods such as~~ Stellarity

That datapack is pretty big and does a lot of changes
You should not expect any end-related mod to properly function when using it

**Comment by yungnickyoung** [comment]
Apologies, but SiverDX is right. Stellarity is quite an extensive overhaul, and on top of that it's done via data pack which makes it much more difficult to add compatibility for. I have no plans on adding compat with it at the moment. However, I do want to make my mod as compatible with other mods as possible, so if you have problems with other mods please open a new issue report and let me know!
