### ISSUE TITLE
[Bug] FabricWaystones getting deleted by player spawn structure

### ISSUE THREAD

**Issue by Hexality** [YUNG-GANG/YUNGs-Better-End-Island#15]
Every single time a player teleports to the end, a new structure gets generated aroudn the player, destroying the waystone used to teleport in the process. Placing the waystone in a structure that has already been generated does not block it from getting destroyed on player teleport.

Using `Fabric 0.14.24`
> Using `BEI v1.0 FABRIC`
> Using `(Wraith) Fabric Waystones 3.0.0`

**Comment by yungnickyoung** [comment]
Addressing this in #22. Will see if I can come up with a better solution
