### ISSUE TITLE
Singleplayer world crashed while end dragon spawned

### ISSUE THREAD

**Issue by liangmoe** [YUNG-GANG/YUNGs-Better-End-Island#21]
crash report: https://mclo.gs/WTUb2ap

**Comment by yungnickyoung** [comment]
Sorry, to be honest I'm not really sure what could be causing this. I haven't really seen an issue of duplicate entity tracking entries before.

**Comment by liangmoe** [comment]
Yeah now i cant reproduce this issue again for some reason, i would close this git issue now untill a find the exact reason, thanks!

**Comment by liangmoe** [comment]
it is [very many player (forge)](https://modrinth.com/mod/vmp-forge), once i remove it the game wont crash anymore
