### ISSUE TITLE
Does the spawn platform reset on purpose? 

### ISSUE THREAD

**Issue by AnasterianSunstrider** [YUNG-GANG/YUNGs-Better-End-Island#22]
It seems that everytime I enter the end, the spawn platform resets any placed or removed blocks. If this is intended, please add configuration to let us turn it off, and if it's a bug, please fix it.

**Comment by yungnickyoung** [comment]
Yeah this is intentional, it's replicating vanilla behavior to ensure there is a block for players to stand on when they teleport to the End. But I agree, it could be implemented better.

**Comment by AnasterianSunstrider** [comment]
I see, thanks for the reply.

**Comment by yungnickyoung** [comment]
I've added a config option for using the vanilla obsidian spawn platform instead of our enhanced one, so if you want to redesign the spawn platform like you would in vanilla you can now do so!
