### ISSUE TITLE
Does the fix to MoreDragonEggs mod in 2.0.5 affect any dragon egg replenishing mod? Ie. "Vanilla Refresh"

### ISSUE THREAD

**Issue by hiimrickross** [YUNG-GANG/YUNGs-Better-End-Island#24]
Hi, apologies for re-opening a related issue, but I was wondering if the way you fixed the replenishing dragon egg drops on each successive kill for More Dragon Eggs mod would allow other mods whos objective is to do the same thing, work also? Or do they require specific compatibility too.

The Vanilla Refresh mod does a number of nice things for the game, toggleable, and one of them is a new egg (with a spawning animation! unlike MDE) on each kill, just like MDE. https://modrinth.com/datapack/vanilla-refresh

**Comment by yungnickyoung** [comment]
It's specifically for MDE atm. I can look into adding compat for that mod as well though

**Comment by hiimrickross** [comment]
that would be awesome.. i don't know how difficult doing so is though.. if it's too much trouble I can disable it ( vanilla refresh has wonderful live ui console in game to toggle things real time) and just use the MDE mod. But I like the fact that VR has a special animation of the egg falling down.

**Comment by yungnickyoung** [comment]
Unfortunately it's not too feasible for me to add compat for Vanilla Refresh since it's implemented as a data pack

**Comment by hiimrickross** [comment]
> Unfortunately it's not too feasible for me to add compat for Vanilla Refresh since it's implemented as a data pack

I see, that's a shame. Well that's alright, I should be able to disable to dragon egg module and put the More Dragon Eggs mod back in. Thank you for your time

**Comment by JenniferDevelopez** [comment]
> > Unfortunately it's not too feasible for me to add compat for Vanilla Refresh since it's implemented as a data pack
> 
> I see, that's a shame. Well that's alright, I should be able to disable to dragon egg module and put the More Dragon Eggs mod back in. Thank you for your time

How did you solve the dragon egg replenish?

**Comment by ryanbcampbell** [comment]
Any possibility that this is interfering with the Dragon Mounts: Legacy mods ability to refresh the dragon egg after each kill? Everything that I'm seeing as I'm looking through the .jar directories points that it should be working, but I've heard that there are some things that this mod could potentially be affecting?

**Comment by yungnickyoung** [comment]
The newest version of BEI on Modrinth for 1.20.1 and 1.20.4 adds a config that includes an option for spawning a dragon egg every time the dragon is defeated. That should hopefully solve this for good!
