### ISSUE TITLE
The "/end_island" command can't be used

### ISSUE THREAD

**Issue by KazeShukufuku** [YUNG-GANG/YUNGs-Better-End-Island#3]
I try to use /end_island to restore the End, but Minecraft thinks the command is not existed.

**Comment by yungnickyoung** [comment]
Are you on Forge? If so, I think this is a bug with my API. Restart your client and try again. It should be there within a few tries.

**Comment by Kata1337** [comment]
I also cannot use the command.  MC 1.20.1, Forge 47.1.47

Also, when i killed the dragon, no dragon egg appeared :/

**Comment by yungnickyoung** [comment]
Fixed with YUNG's API v4.0.3! Please open a new issue report if the problem persists
