### ISSUE TITLE
Adventurez compatibility?

### ISSUE THREAD

**Issue by Ejz9** [YUNG-GANG/YUNGs-Better-End-Island#30]
This mod makes it so the egg doesn't respawn on successive dragon kills. Can this be a config option or something? I love what this does to the island. Just wish the egg would respawn for my players from AdventureZ. Which I know this overwrites the method to. Regardless thank you for your work.

**Comment by yungnickyoung** [comment]
Just added a config option for always spawning a dragon egg on the latest version of BEI for 1.20.1 and 1.20.4!
