### ISSUE TITLE
[Suggestion] Add a config file.

### ISSUE THREAD

**Issue by ghost** [YUNG-GANG/YUNGs-Better-End-Island#5]
Add a configuration file as IntM4rco suggested, but for other purposes. Namely, to disable controversial features. 

Such as turning obsidian into crying obsidian in pillars, tower and etc.

Also the possibility of returning vanilla structures. Since for example spawn platform does not give the will of imagination to create something other than the specified style, which is obviously wrong.

**Comment by NolanHewitt** [comment]
I would like this as well. I would like to be able to return the vanilla center platform, but I really like the new obsidian pillars and end gateways and wish I could still have those.

**Comment by yungnickyoung** [comment]
Added in latest versions for 1.20.1 and 1.20.4! Only a couple of basic starting options for now but we may add more in the future.
