### ISSUE TITLE
Exit Portal Tower can fail to generate + Be incomplete

### ISSUE THREAD

**Issue by Inonedn** [YUNG-GANG/YUNGs-Better-End-Island#6]
[latest.log](https://github.com/yungnickyoung/YUNGs-Better-End-Island/files/12689143/latest.log)
![image](https://github.com/yungnickyoung/YUNGs-Better-End-Island/assets/36087299/c6bf500e-d2d6-43db-b84f-7b0e5f29f4b1)

**Comment by yungnickyoung** [comment]
With the newest version, v2.0.3, the `/end_island reset` command should fix this. If your portal has generated at the bottom of the map, try using `/end_island reset true`, but **only use it once and back up your world before doing so!**
