### ISSUE TITLE
Incompatibility with Stellarity

### ISSUE THREAD

**Issue by XeeXeeVR** [YUNG-GANG/YUNGs-Better-End-Island#7]
The Stellarity mod changes the island into the dragon's den biome which causes the center structure to spawn far above the island.  The structure is so far up in the air that I have to build to it to even trigger the dragon summoning and when it does fully summon it just dies immediately.  On some occasions the full structure spawns in the air and sometimes it just spawns as a + shaped box with the end crystals on top. 

After testing without BEI turns out the mod generates its own custom end towers and a center platform.  BEI replaces the towers but while it deletes the center platform its causing its whole floating far up in the sky with the center structure issue

This is occuring on 1.20.1 with what is currently the most recent version of both mods

**Comment by MrGreenTea** [comment]
For me the structures look right, but the dragon just instantly explodes and dies when spawning.

**Comment by yungnickyoung** [comment]
Unfortunately Stellarity is quite an extensive overhaul, plus it's a data pack so it's difficult to make it compatible. At the moment I don't have any plans for adding Stellarity compatibility.
